# THIS IS THE CONFIGURATION FILE FOR PYCAMWATCHER PARAMETERS


# IMAGE PARAMETERS
IMAGE_COUNTER_MAXIMUM=1 # THE AMOUNT OF IMAGES OF AN EXECUTION OF THE PROGRAM
# IMAGE_COUNTER_MAXIMUM=0 IS EQUAL TO NO MAXIMUM
IMAGE_WIDTH=640 # IN PIXELS
IMAGE_HEIGHT=480 # IN PIXELS
IMAGE_FORMAT="jpg"
IMAGE_QUALITY="high"
IMAGE_NAME_SEPARATOR="_"
IMAGE_FIRST_NAME="image"
IMAGE_PATH="img"
IMAGE_PREVIEW=False
IMAGE_PREVIEW_TIMEOUT=10

# TIME PARAMETERS
TIME_PER_IMAGE=1 # IN SECONDS (DEFAULT VALUE IS 1)
TIME_OF_SLEEP=0.01 # IN SECONDS (DEFAULT VALUE IS 0.01)

